services:
    neo:
        image: unaio/neo:04dd2e3
        labels:
            - "promtail.job=neo"
            - "traefik.enable=true"
            - "traefik.http.routers.neo.rule=Host(`{{ host }}`) && PathPrefix(`/`)"
            - "traefik.http.services.neo.loadbalancer.server.port=3000"
            # redirect fix for phpmyadmin
            - 'traefik.http.middlewares.pma-redirect.redirectregex.regex=^(https?://[^/]+)/index\.php\?route=/$'
            - 'traefik.http.middlewares.pma-redirect.redirectregex.replacement=$1/phpmyadmin/'
            - "traefik.http.middlewares.pma-redirect.redirectregex.permanent=true"
            - "traefik.http.routers.neo.middlewares=pma-redirect"            
        restart: always
        environment:
            UNA_API_KEY: "${NEO_UNA_API_KEY}"
            NEXT_PUBLIC_UNA_URL: "${NEO_UNA_URL}"
            UNA_URL: "${NEO_UNA_URL}"
        working_dir: /app
        command: >
            sh -c "
                node /tmp/maintenance.js &
                PID_MAINTENANCE=$$!;
                yarn --cwd apps/next build;
                kill -9 $$PID_MAINTENANCE || true;
                wait $$PID_MAINTENANCE || true;
                exec yarn --cwd apps/next start
            "
        init: true
        volumes:
            - ./neo/images_allowlist.js:/app/packages/app/customization/config/images_allowlist.js
            - ./neo/static.js:/app/packages/app/customization/static.js
            - ./neo/settings.js:/app/packages/app/customization/settings.js
            - ./neo/global.css:/app/packages/app/customization/design/styles/global.css
            - ./neo/maintenance.js:/tmp/maintenance.js
        networks:
            - proxy
    soketi:
        image: quay.io/soketi/soketi:e446df8e3e06b8430d75cf58555bc409bf240a4e-16-alpine
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.soketi.rule=Host(`{{ host }}`) && PathPrefix(`/app`)"
            - "traefik.http.services.soketi.loadbalancer.server.port=6001"
            - "promtail.job=soketi"
        restart: always
        environment:
            SOKETI_DEFAULT_APP_ID: main
            SOKETI_DEFAULT_APP_KEY: main
            SOKETI_DEFAULT_APP_SECRET: "{{ soketi_secret }}"
#        volumes:
#            - ./www/ssl:/opt/soketi/config/ssl
#            - ./cnf/jot-ssl-config.json:/opt/jot-server/config/config.json
        ports:
            - 6001:6001
        networks:
            - proxy